### ISSUE TITLE
Loading docking-protein-protein example with guru catalog fails.

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#11]
Loading it with basic or intermediate catalog works, but with guru level it throws following error:

```
RangeError: Maximum call stack size exceeded
    at l.validate (vendor.e501f282.js:228:52669)
    at z (index.0b7abd16.js:2:1563)
    at index.0b7abd16.js:2:1297
    at Array.map (<anonymous>)
    at Ee (index.0b7abd16.js:2:1184)
    at loadWorkflowArchive (index.0b7abd16.js:2:3472)
    at async onClick (index.0b7abd16.js:2:4699)
```

**Comment by sverhoeven** [comment]
Loading the `double_topoaa.zip` example from the guru catalog works.
